name: DevSecOpsCI

on:
  pull_request:
    branches:
      - devops

jobs:

  Code-Quality:
    uses: ./.github/workflows/code-lint.yml

  Secret-Scanning:
    uses: ./.github/workflows/secret-scanning.yml

  Dependency-Scan:
    uses: ./.github/workflows/dependency-scan.yml

  Docker-Scans:
    uses: ./.github/workflows/docker-scans.yml

  Sonar-Scan:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit

#added comment to test the workflow for testing purposes