name: Docker lint and Scan
on:
    workflow_call:

jobs:
    Docker-Scans:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Hadolint - Main
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile

            - name: Hadolint - Migration
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: scripts/Dockerfile.migration

            # -------------------------
            # Build Main Image
            # -------------------------

            - name: Build Main Docker Image
              run: |
                docker build \
                    -f Dockerfile \
                    -t ${{ vars.DOCKERHUB_USERNAME }}/e-commerce-app:latest .

            # -------------------------
            # Build Migration Image
            # -------------------------

            - name: Build Migration Docker Image
              run: |
                docker build \
                    -f scripts/Dockerfile.migration \
                    -t ${{ vars.DOCKERHUB_USERNAME }}/e-commerce-migration:latest .

            # -------------------------
            # Trivy - Main Image
            # -------------------------

            - name: Trivy Scan - Main
              uses: aquasecurity/trivy-action@v0.36.0
              continue-on-error: true
              with:
                image-ref: '${{ vars.DOCKERHUB_USERNAME }}/e-commerce-app:latest'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL'

            # -------------------------
            # Trivy - Migration Image
            # -------------------------

            - name: Trivy Scan - Migration
              uses: aquasecurity/trivy-action@v0.36.0
              continue-on-error: true
              with:
                image-ref: '${{ vars.DOCKERHUB_USERNAME }}/e-commerce-migration:latest'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL'