name: Image-Push

on:
    workflow_call:

jobs:
    Image-Push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
              with:
                fetch-depth: 0

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              run: |
                docker build \
                    -t ${{ vars.DOCKERHUB_USERNAME }}/easyshop:latest .
                docker push ${{ vars.DOCKERHUB_USERNAME }}/easyshop:latest
                cd scripts
                docker build \
                    -f scripts/Dockerfile.migration \
                    -t ${{ vars.DOCKERHUB_USERNAME }}/easyshop-migration:latest .
                docker push ${{ vars.DOCKERHUB_USERNAME }}/easyshop-migration:latest